#!/bin/bash

# Logo
curl -s https://raw.githubusercontent.com/cryptoportalua/scripts/refs/heads/main/utils/logo | bash

PS3='Select an action: '
options=(
  "Install GaiaNet"
  "Update GaiaNet"
  "Delete GaiaNet"
  "Exit"
)

select opt in "${options[@]}"
do
  case $opt in
    #================================================================
    "Install GaiaNet")
      echo "Installing GaiaNet..."
      
      curl -sSfL 'https://github.com/GaiaNet-AI/gaianet-node/releases/latest/download/install.sh' | bash

      sed -i "s/device-cf543e37e491609d4c3f82d6/device-9253f979f44d8dae0cc5dde5/g" ~/gaianet/gaia-frp/frpc.toml

      read -p 'Введіть нову адресу: ' new_addr

      sed -i "s/0x[a-f0-9]\{40\}/${new_addr}/g" ~/gaianet/gaia-frp/frpc.toml
      sed -i "s/localPort = 8080/localPort = 8282/g" ~/gaianet/gaia-frp/frpc.toml
      sed -i 's/"llamaedge_port": "8080"/"llamaedge_port": "8282"/g' ~/gaianet/config.json

      gaianet init
      gaianet start
      break
      ;;
    #================================================================
    "Update GaiaNet")
      echo "Updating GaiaNet..."

      gaianet stop

      curl -sSfL 'https://github.com/GaiaNet-AI/gaianet-node/releases/latest/download/install.sh' | bash

      source $HOME/.bashrc

      gaianet start
      break
      ;;
    #================================================================
    "Delete GaiaNet")
      echo "Deleting GaiaNet..."
      gaianet stop
      rm -rf ~/gaianet*
      rm -rf ~/crocogaia
      echo "GaiaNet deleted"
      break
      ;;
    #================================================================
    "Exit")
      echo "Exiting script."
      exit
      ;;
    *)
      echo "Invalid option, please try again."
      ;;
  esac
done
